### ISSUE TITLE
Insight-UI?

### ISSUE THREAD

**Issue by Berndinox** [m00re/bws-docker#1]
Hy,
would it be possible to enable Insight-UI?
and disable/remove the wallet?

I would like to run a "info" service only...
:)
Thanks alot, BR

**Comment by m00re** [comment]
The Docker image comes with Insight-API included. I think it should not be a big step to add Insight-UI as well. But since I am not using the Docker image anymore myself, I am not maintaining it any longer. The image is also quite "old" and in order to deal with the recent forks it would make sense to incorporate a more recent Bitcoind version. Apart from that, Bitpay has released more recent versions of Bitcore as well.

I will close this issue now because I will not continue working on this Docker image.

Best regards
Jens
